### ISSUE TITLE
Bout-wise tracking

### ISSUE THREAD

**Issue by talmo** [talmolab/sleap-mot#7]
When initializing with `Labels` that already have some pre-assigned tracks, we should start off from bouts of existing tracks and continue from those.

Ideally, this should be handled at the individual contiguous bout-level.

For example, consider this scenario:

```
Frame 0: untracked
Frame 1: tracked
Frame 2: tracked
Frame 3: tracked
Frame 4: tracked
Frame 5: untracked
Frame 6: untracked
Frame 7: tracked
Frame 8: tracked
Frame 9: tracked
Frame 10: untracked
Frame 11: untracked
```

Let's ignore frame 0 for now since this depends on #8.

The next contiguous set of tracked frames then is frames 1-4. In this case, we want to start from at frame 5, and match it to the tracks available in frames 1-4.

To do this, we need to be able to find these "gaps" of untracked frames, then populate our candidate buffers with the data from frames 1-4 without doing any new assignment.

Once the buffers are the correct state, we can now track frames 5 and 6 in "forward mode".

The same process will happen again for frames 10 and 11, using the data from frames 7-9.

In this mode, we are explicitly ignoring previously untracked frames that might have been assigned tracks now (e.g., frames 5 and 6) even if they fit in the tracking buffer. This allows us to safely ignore unreliable detections that might work against us as distractors, and allows for parallelization across these "gap tracklets".

**Note:** For the first pass implementation, frame 10 will be added to the buffers as usual, despite the fact that it may contain unreliable detections. We will handle the decision of whether to include a set of detections in the buffer in #10.

See also: #8 which defines the more generalized grouping algorithm a bit more explicitly.

## Checklist
- [ ] Create helper methods to populate track buffers and initialize the state of the tracker at an arbitrary frame with arbitrary data.
    - This should be a method in the `Tracker` class that takes a list of `LabeledFrame`s, empties (some? all?) track buffers, loops over the frames and adds the tracked instances to the appropriate buffers.
- [ ] Detect contiguous chunks of frames that have pre-assigned tracks, and pair them with contiguous chunks of frames that need tracking.
- [ ] Integration: make a higher level API that can take a `Labels` object, segment it into chunks of `(tracked, untracked)` pairs of frame sequences, then runs the tracking on each bout.
- [ ] **Special case:** handling scenarios where we have frames where only some instances have pre-assigned tracks (but not all) will require special logic since now it means that the segmentation of tracked-vs-untracked is a bit more ambiguous.
    - We might want to do it in two passes?
    - This will be important for RFID when we'll only know the identity for sure for a subset of the animals.
